### ISSUE TITLE
firefox small bug

### ISSUE THREAD

**Issue by vanja-san** [poletaevvlad/anime-list-popup#1]
Проще на русском, когда я меняю значение серии например 2/0 на 3/0, то расширение попросту запрашивает пометить как "completed", ну а если я нажимаю нет, то серии попросту сбрасываются до 0/0. То есть где неизвестное количество серий, там проблемка при редактировании.

**Comment by poletaevvlad** [comment]
Спасибо за баг-репорт и за заинтересованность в расширении.

Этот баг исправлен в PR #2. Я отправил обновленную версию 1.2.0 на проверку в магазины расширений Google Chrome и Firefox. Исправления должны стать доступны в близжайшее время.

Если проблема не будет исправлена или возникнут новые проблемы или рекоммендации, пожалуйста, сообщите в этом или новом issue.

**Comment by vanja-san** [comment]
@poletaevvlad вам спасибо за такое удобное расширение, с радостью им пользуюсь. Проблема и правда уже исправлена, я рад. 😊
