### ISSUE TITLE
I can’t log into my MyAnimeList account

### ISSUE THREAD

**Issue by Proxy-E23** [poletaevvlad/anime-list-popup#10]
I’m trying to log into MyAnimeList using Edge, but I keep getting an error

![image](https://user-images.githubusercontent.com/79614894/229055387-b8d3df61-f97d-469c-aef2-15d17a1272f5.png)

**Comment by poletaevvlad** [comment]
Thank you for bringing this issue to my attention, unfortunately I haven't had a chance to investigate this sooner or catch it myself.

Apparently, the extension ID on Chromium-based browsers has changed. Not sure how that happen, but I've updated the oAuth configuration on MAL's side and you should be able to log into your account. No update is necessary.

Please, reach out if the issue persists.
