### ISSUE TITLE
Error loading the cover image.

### ISSUE THREAD

**Issue by Proxy-E23** [poletaevvlad/anime-list-popup#11]
Seems like there's an issue with loading the cover images, but I can still update the status and mark chapters as viewed.

I'm currently using Firefox, so I'm not sure if this issue also occurs in other browsers.

Update: I checked in Edge as well and the same issue.

![imagen](https://github.com/poletaevvlad/anime-list-popup/assets/79614894/266baf68-34ad-4f2e-bf53-b1ea843df857)

**Comment by poletaevvlad** [comment]
Thank you for the issue, I was able to reproduce the issue on my end. MyAnimeList has changed the domain name from which the images are referenced by the API.

This extension has a strict content security policy: the manifest forbids the loading of resources from domains not explicitly listed. This caused the issue where the image loading from the new domain was restricted. I've updated the policy and will submit the new version for review later today. Then its up to Mozilla and Google to deliver the update.
