### ISSUE TITLE
[запрос функции] Поиск

### ISSUE THREAD

**Issue by vanja-san** [poletaevvlad/anime-list-popup#3]
Есть ли возможность добавить поиск (например в верхнюю панель)? Было бы удобно искать требуемое аниме. Часто смотрю и меняю серии, но очень иногда долго искать просто листая мышкой вниз. 😳

**Comment by poletaevvlad** [comment]
Реализовано в версии 1.3.0, которая уже была опубликовала для Firefox и должна вскоре должна стать доступной для Chrome. Поиск работает по всему MAL и не ограничен добавленными аниме из-за ограничений API. В случае обнаружения проблем, можете переоткрыть этот issue.
