### ISSUE TITLE
Проблемка с поиском

### ISSUE THREAD

**Issue by vanja-san** [poletaevvlad/anime-list-popup#8]
В общем, когда я пытаюсь искать длинное название то происходит ошибка. Сначала я думал что ошибка на стороне самого MAL, но после 30-го раза мне всё же кажется это в самом расширении ошибочка.:

![изображение](https://user-images.githubusercontent.com/7201687/211167924-5084555c-8b73-414b-b185-e3ae159c11f0.png)

**Comment by poletaevvlad** [comment]
Спасибо за баг-репорт.

То, что расширение не обрабатывет эту ошибку --- однозначно, баг. В корне её лежит недокументированное ограничение MAL: их API отказывается обрабатывать запросы длиннее 64 символов и короче 3 не считая пробелы в начале и в конце запроса.

Я думаю в следующей версии обрезать запрос до 64 символов, я сомневаюсь, что это сильно повлияет на результаты.

**Comment by vanja-san** [comment]
@poletaevvlad получается такие названия будут выдавать ошибку? В принципе решение простое, искать пол названия и тогда находит.

![изображение](https://user-images.githubusercontent.com/7201687/212179419-85af375d-160d-47ab-aa5e-cfbebe5b746e.png)

**Comment by poletaevvlad** [comment]
В близжайшее время должно прийти автоматическое обновление 

![Screen Shot 2023-01-14 at 23 29 09](https://user-images.githubusercontent.com/1760698/212497864-072508a5-ea1f-4cc9-8750-87e6910d506a.png)

**Comment by vanja-san** [comment]
@poletaevvlad невероятно, спасибо!
